### PR TITLE
General clean up

### PR DESCRIPTION
**Pull request by BuyMyMojo**
This is mostly general cleanup suggested by clippy with the extra additionsbeing adding `Eq` to TemplateErrorKind and setting a couple functions to const

### CODE REVIEW

**Review by hasezoey — CHANGES_REQUESTED** [review]
please remove the clippy clean-up commits, they seem to use the stable clippy and also not the config, run clippy in this project through [`clippy.sh`](https://github.com/hasezoey/new_string_template/blob/master/clippy.sh)

---

otherwise looks good

**Comment by BuyMyMojo** [comment]
I think that sould be it, right?

Also unrelated to this pull request but is there a reason you use implicit returns? I'm curious.

**Comment by hasezoey** [comment]
> Also unrelated to this pull request but is there a reason you use implicit returns?

you mean explicit `return` statements? because i am just a developer who is used to it and personally think it is better readable than differentiating between a `;` and a missing one (because with a `;` is not returning anymore)

**Comment by BuyMyMojo** [comment]
That makes sense to me 👍

**Review by hasezoey — APPROVED** [review]
updated commits to drop reverted ones and apply formatting & clippy directly to the commits introducing it, also changes some commit messages to be in-line with [CONTRIBUTING.md](https://github.com/hasezoey/new_string_template/blob/master/.github/CONTRIBUTING.md)'s guidelines (which includes lower-cased first letter of `subject` and not longer than 100 character long lines)

are you fine with the changes?

**Comment by BuyMyMojo** [comment]
Yea that sounds perfect, thank you!

**Pull request merged**
